### ISSUE TITLE
Llama2-70b-chat-hf causes segmentation fault when used with TPP

### ISSUE THREAD

**Issue by dineshchitlangia** [libxsmm/tpp-pytorch-extension#3]
This issue only happens with 70B.
7B and 13B work fine with TPP.

Here is the stacktrace.
```
my_size=1 N=64 H=128
Traceback (most recent call last):
  File "/home/dc/large_model/LLM_ALL.py", line 76, in <module>
    model = tpx.llm.llm_common.jit_trace_model(model, tokenizer, num_beams)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/tpp_pytorch_extension-0.0.1-py3.9-linux-x86_64.egg/tpp_pytorch_extension/llm/llm_common.py", line 269, in jit_trace_model
    traced_model = torch.jit.trace(model, jit_inputs, strict=False)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/jit/_trace.py", line 798, in trace
    return trace_module(
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/jit/_trace.py", line 1065, in trace_module
    module._c._create_method_from_trace(
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1034, in forward
    outputs = self.model(
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 922, in forward
    layer_outputs = decoder_layer(
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  **File "/home/dc/anaconda3/envs/llma2-env/lib/python3.9/site-packages/tpp_pytorch_extension-0.0.1-py3.9-linux-x86_64.egg/tpp_pytorch_extension/llm/fused_llama_infer.py", line 107, in forward
    outputs = self.cpp_block.forward(inputs, past_key_value, use_cache)
RuntimeError: shape '[1, 4, 64, 128]' is invalid for input of size 4096**

LIBXSMM_VERSION: main_stable-1.17-3660 (25693772)
CPX/SP      TRY    JIT    STA    COL
   0..13      0      0      0      0
  14..23     32     32      0      0
  24..64    144    144      0      1
    > 64     52     52      0      4
Registry and code: 13 MB + 3 MB (gemm=228 gemv=60 meltw=184)
Command: python3 LLM_ALL.py
Uptime: 495.766315 s
Segmentation fault (core dumped)
```

Steps to repro.

//Load Model
```
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-70b-chat-hf", torch_dtype=Precision, low_cpu_mem_usage=True, return_dict=False)
model = model.to(memory_format=torch.channels_last)
model = model.eval()

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-70b-chat-hf", use_fast=False, model_max_length=2048, padding_side="left")
       
```
//apply TPP
```
from tpp_pytorch_extension.llm.fused_llama_infer import OptimizeModelForLlama
import tpp_pytorch_extension as tpx
OptimizeModelForLlama(model,dtype=torch.bfloat16, device='cpu')
model = tpx.llm.llm_common.jit_trace_model(model, tokenizer, num_beams)
```
where num_beams=4

//Infer
```
torch._C._jit_set_texpr_fuser_enabled(False)
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
outputs   = model.generate(input_ids, num_beams=4, max_new_tokens=32, min_new_tokens=32, early_stopping=True, pad_token_id=tokenizer.pad_token_id, do_sample = False)
```

**Comment by ddkalamk** [comment]
Hi @dineshchitlangia,

Thanks for reporting. LLaMA-2 is not yet tested / supported in extension. Specifically, Grouped Query Attention (GQA) used in llama2 70B model is not supported yet. Most likely that is a cause of seg-fault. We are working on it.

**Comment by dineshchitlangia** [comment]
Thanks @ddkalamk for a quick response.

**Comment by dineshchitlangia** [comment]
@ddkalamk Hi Dhiraj, thank you for adding the changes. In my test, it still does not work, however, it gives a different error.
There is no segmentation fault but it seems like an issue with transformers library now.

`Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 15/15 [01:40<00:00,  6.69s/it]
Traceback (most recent call last):
  File "/home/dc/large_model/experiment.py", line 78, in <module>
    model = tpx.llm.llm_common.jit_trace_model(model, tokenizer, num_beams)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/tpp_pytorch_extension-0.0.1-py3.11-linux-x86_64.egg/tpp_pytorch_extension/llm/llm_common.py", line 345, in jit_trace_model
    traced_model = torch.jit.trace(model, jit_inputs, strict=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/jit/_trace.py", line 798, in trace
    return trace_module(
           ^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/jit/_trace.py", line 1065, in trace_module
    module._c._create_method_from_trace(
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1174, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1000, in forward
    past_key_values = DynamicCache.from_legacy_cache(past_key_values)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dc/anaconda3/envs/70benv/lib/python3.11/site-packages/transformers/cache_utils.py", line 163, in from_legacy_cache
    key_states, value_states = past_key_values[layer_idx]
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
`

**Comment by ddkalamk** [comment]
what is your transformers version? Can you try with transformers==4.31.0, if you are using a different one?

**Comment by dineshchitlangia** [comment]
@ddkalamk  mine is 4.36.0
I am trying now with 4.31.0

**Comment by dineshchitlangia** [comment]
@ddkalamk It seems to work with 4.31.0.
I will do some more testing and report back if I encounter new issues.
Thank you.

**Comment by ddkalamk** [comment]
Should be fixed with commit ID [9f8c74ed](https://github.com/libxsmm/tpp-pytorch-extension/commit/9f8c74ed570824e9355b2e085c4c94d91991a0a9)

Closing the issue, please reopen if you see the issue...

**Comment by dineshchitlangia** [comment]
@ddkalamk - Apologies for delay in getting back. I can confirm the issue is resolved. Thank you.
